### ISSUE TITLE
A massive number of simultaneous jobs can result in an Timeout

### ISSUE THREAD

**Issue by proemmer** [proemmer/dacs7#21]
But in the wireshark trace there is no timeout visible.

**Comment by rjanak** [comment]
I stumbled upon this project looking for an alternative for Snet plus. But I think the issue I might still face since my issue with Snet plus is that during multiple simultaneous jobs I'm getting timeout and other issues. Could this be from PLC side or from the library.

**Comment by proemmer** [comment]
The current version of dacs7 (2.2.3) contains some fixes facing this problem. So this problem should be fixed in the most cases. 
But it also depends on the used plc and the data (BigData - SmallPduSize) you like to read or write.

PLC Limitations:
* PDU Size
* Max Concurrent Jobs
* Performance of the PLC

If you continue to have this problem with dacs7 please provide a Wireshark (https://wiki.wireshark.org/S7comm) trace file of this behavior so that we can investigate further.

**Comment by rjanak** [comment]
Okay, thanks for the information.

**Comment by rjanak** [comment]
I'm trying out Dacs7 library now. 
I'm reading from the location DB1.DBD60. From the documentation I see that I have to do something like this, but not sure about string after address. Could you please help me out.
await _client.ReadAsync( ReadItem.CreateFromTag("DB1.DBD60,," ) );

**Comment by proemmer** [comment]
The Syntax of the tag methods are well described in the ***using tag methods*** section [(see github readme)](https://github.com/proemmer/dacs7#using-tag-methods)

here again the syntax :
`Area.Offset,DataType[,Length]`

so in your case:
`ReadItem.CreateFromTag("DB1.60,dw")`

or if you like to use a non tag based addressing you also can use this:
`ReadItem.Create<uint>("DB1", 60)`

**Comment by rjanak** [comment]
@proemmer got it, thank you
